### ISSUE TITLE
Dissolution legacy doesn't build

### ISSUE THREAD

**Issue by Derailedzack** [Ladysnake/Dissolution-Legacy#21]
Dissolution legacy fails to build because of a broken maven repo.

**Comment by Pyrofab** [comment]
Could you open a PR to fix that maybe ?

**Comment by Derailedzack** [comment]
Yes. What license is Epic Siege under?

**Comment by Derailedzack** [comment]
I may just comment out the epic siege mod. This problem affects all version of dissolution legacy. I will close the issue when the pull request is accepted or denied
